# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60
          
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Lint lib
      working-directory: plugins-lib
      run: go vet ./...

    - name: Lint host
      working-directory: plugins-host
      run: go vet ./...

    - name: Lint example
      working-directory: examplecli
      run: go vet ./...

    - name: Build lib
      working-directory: plugins-lib
      run: go build -v ./...

    - name: Build host
      working-directory: plugins-host
      run: go build -v ./...

    - name: Build example
      working-directory: examplecli
      run: go build -v ./...

    - name: Test lib
      working-directory: plugins-lib
      run: go test -v ./...

    - name: Test host
      working-directory: plugins-host
      run: go test -v ./...

    - name: Test example
      working-directory: examplecli
      run: go test -v ./...
